name: Deploy Angular SPA to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js 20.12.0
        uses: actions/setup-node@v1
        with:
          node-version: '20.12.0'
      - name: Build
        run: |
          npm install -g @angular/cli
          npm install --legacy-peer-deps
          ng build --prod --base-href=""
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/git-catalogue
